# Generated by Django 3.2.4 on 2021-06-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdapp', '0002_auto_20210607_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_name',
            field=models.CharField(max_length=50),
        ),
    ]
